mainSections:
  - posts
description: Eureka is a elegant and powerful theme for Hugo.

repoURL:
# If it is a Github repo, leave blank
repoEditURL:

dateFormat:

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: C. Wang
publisherLogo:

highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/master/build/languages for available languages.
    languages:
      - dart
    # See https://github.com/highlightjs/cdn-release/tree/master/build/styles for available styles.
    style: solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   leqno:

comment:
  # Options: disqus, commento and valine.
  platform:

  disqus:
    shortname:

  commento:
    # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
    url:

  valine:
    # See Valine Document https://valine.js.org/
    # you can specify the Valine version by yourself!
    version: 1.4.14
    appId:
    appKey:
    placeholder: Just go go
    avatar: mp
    meta: ['nick','mail','link']
    pageSize: 10
    lang: zh-CN
    visitor: false
    highlight: true
    avatarForce: false
    recordIP: false
    serverURLs: http[s]://[tab/us].avoscloud.com
    emojiCDN:
    emojiMaps: null
    enableQQ: false
    requiredFields: []